In [9]:
import numpy as np

x_train = [
    [[1], [2], [3]],
    [[2], [3], [4]],
    [[3], [4], [5]],
    [[6], [7], [8]],
    [[7], [8], [9]],
]
y_train = [4, 5, 6, 9, 10]
# 将上面数组的转换为张量
x_train = np.asarray(x_train)
y_train = np.asarray(y_train)
print("x_train shape:", x_train.shape)
print("y_train shape:", y_train.shape)
print("x_train", x_train)
print("y_train", y_train)
# 待预测数据
x_test = np.asarray([[[5], [6], [7]]])

x_train shape: (5, 3, 1)
y_train shape: (5,)
x_train [[[1]
  [2]
  [3]]

 [[2]
  [3]
  [4]]

 [[3]
  [4]
  [5]]

 [[6]
  [7]
  [8]]

 [[7]
  [8]
  [9]]]
y_train [ 4  5  6  9 10]


In [11]:
# 构建网络层
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.layers import LSTM, Dense, Dropout, Embedding
from tensorflow.keras.models import Sequential

model = Sequential()
model.add(LSTM(100, input_shape=(2, 1), return_sequences=False))
model.add(Dense(1))
model.compile(loss="mse", optimizer="adam")
# 网络层参数打印
model.summary()

# 训练
model.fit(x_train, y_train, epochs=500, verbose=1)

# 预测
print(model.predict(x_test))


# 结果
# Epoch 497/500
#  - 0s - loss: 0.0014
# Epoch 498/500
#  - 0s - loss: 0.0013
# Epoch 499/500
#  - 0s - loss: 0.0012
# Epoch 500/500
#  - 0s - loss: 0.0012
# [[1.0567069]]

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_6 (LSTM)                (None, 100)               40800     
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 101       
Total params: 40,901
Trainable params: 40,901
Non-trainable params: 0
_________________________________________________________________
Epoch 1/500
1/1 [==============================] - 1s 1s/step - loss: 51.7627
Epoch 2/500
1/1 [==============================] - 0s 4ms/step - loss: 50.1627
Epoch 3/500
1/1 [==============================] - 0s 4ms/step - loss: 48.6015
Epoch 4/500
1/1 [==============================] - 0s 3ms/step - loss: 47.0771
Epoch 5/500
1/1 [==============================] - 0s 3ms/step - loss: 45.5876
Epoch 6/500
1/1 [==============================] - 0s 4ms/step - loss: 44.1306
Epoch 7/500
1/1 [======================